apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction
          image: budgetacr.azurecr.io/transactionprod:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: DATABASE_URL
              value: "mysql://root:root@mysql-service:3306/transactiondb"  # Common database URL
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
